### ISSUE TITLE
Pages and Router Setup

### ISSUE THREAD

**Issue by sam-warren** [SENG499-Company-4/Frontend#5]
Basic Pages & Router Setup
- [ ] Create router component
- [ ] Create basic pages
- Landing Page / Splash Screen (/)
- Login Page (/login)
- Dashboard page (/dashboard)
- Professor survey (/survey)
- Schedule View (/schedule)
- Schedule Manage (/schedule/manage)
- Schedule Timetable (/schedule/timetable)
- Generate Schedule (/schedule/generate)
- Professor Manage View (/professor/{id})
- Error Page (404/401) (/error)
- [ ] MUI Navbar Component
- [ ] Create basic navigation guard middleware
